title: Narendra Jha
logo: /assets/img/Narendra Jha.jpg
description: Technical Manager with 14+ years of expertise in development and organizing business operations.
show_downloads: true
google_analytics:
theme: jekyll-theme-minimal
